### ISSUE TITLE
Can this target 8.0 instead of 8.3?

### ISSUE THREAD

**Issue by blakebyrnes** [auth0/JWTDecode.swift#10]
When I build, I'm getting an error that JWTDecode targets 8.3.  Thanks!

**Comment by hzalaz** [comment]
If you build with the latest stable Xcode version it should compile without issues. What version are you using?

**Comment by blakebyrnes** [comment]
Oh, strange.  Ok.  Maybe Carthage is somehow automatically getting that 8.3 from somewhere else?  My Cartfile.resolved lists 0.3.1.

**Comment by hzalaz** [comment]
The SDK version is obtained from the installed version of Xcode in your Mac. 
Try running `xcodebuild -version` in the CLI

**Comment by blakebyrnes** [comment]
I’m on 6.4.  Didn’t realize that was what you were asking. Here’s what it’s telling me: Module file's minimum deployment target is ios8.3 v8.3: /Users/.../Carthage/Build/iOS/JWTDecode.framework/Modules/JWTDecode.swiftmodule/arm.swiftmodule

**Comment by hzalaz** [comment]
ok, will decrease the deployment target

**Comment by blakebyrnes** [comment]
Thanks!

**Comment by hzalaz** [comment]
Version [0.3.2](https://github.com/auth0/JWTDecode.swift/releases/tag/0.3.2) now targets 8.0+
