### ISSUE TITLE
Version missing in JWT podscpec 2.4.0 on Github

### ISSUE THREAD

**Issue by mali1989** [auth0/JWTDecode.swift#103]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> In the following podspec

[https://github.com/auth0/JWTDecode.swift/blob/2.4.0/JWTDecode.podspec](https://github.com/auth0/JWTDecode.swift/blob/2.4.0/JWTDecode.podspec)

the version is missing. As I need it for internal referencing purposes - could you please add the corresponding version into the Podspec?

### Reproduction

![podspec](https://user-images.githubusercontent.com/55285856/72993271-67719400-3df5-11ea-9b93-be8eece246ec.PNG)

### Environment

> Please provide the following:

- **Version of this library used:** 2.4.0
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by Widcket** [comment]
Hi @mali1989, the version number is generated by the [command on line 1](https://github.com/auth0/JWTDecode.swift/blob/44895b4888a252c74cb4f945f1cee09b907a9f8e/JWTDecode.podspec#L1).
