### ISSUE TITLE
Support for timestamp expiration date with milliseconds ( 13 digits) 

### ISSUE THREAD

**Issue by radg1596** [auth0/JWTDecode.swift#105]
The computed property "expired" in the class JWT, only works when the number of timestamp expiration digits are 10. Sometimes the backend generates a timestamp with 13 digits (including milliseconds), and this property is always returns false.

Example
let jsonWebToken = try decode(jwtWithUnixExp: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE1ODE3MjMwMzIwMDB9.Ku_xrqNKYgNRvqGvs4hc7TVpbO9pS3vn2wv95f8N2f4")
print(jsonWebToken.expired)

Would be great have a init method for timestamp expiration with 13 digits (Include miliseconds ). I think that maybe its a bit tricky, however I have not idea for another solution.

Example
          let jsonWebToken = try decode(jwtWithUnixExp: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE1ODE3MjMwMzIwMDB9.Ku_xrqNKYgNRvqGvs4hc7TVpbO9pS3vn2wv95f8N2f4")            
            print(jsonWebToken.expired)

I created a local branch with a proposed solution, however I can not do push and pull request. I hope let me try it. 

Your Pod its amazing. Congratulations. Its too util for me.

**Comment by Widcket** [comment]
Hi @radg1596, thanks for reaching out. The library [is already using](https://github.com/auth0/JWTDecode.swift/blob/master/JWTDecode/JWTDecode.swift#L119) `Date(timeIntervalSince1970:)` to convert the `Double` Unix timestamp to a `Date`. That initializer expects seconds, so if you have milliseconds you need to convert them first.
