### ISSUE TITLE
Test target dependencies failed to install via SSH

### ISSUE THREAD

**Issue by dolzhenko-tony** [auth0/JWTDecode.swift#109]
By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

<img width="628" alt="Screenshot 2020-04-23 at 14 14 17" src="https://user-images.githubusercontent.com/5227857/80094848-a4256680-856f-11ea-91aa-3e3c8845b709.png">

Test target dependencies not installing if SSH used. Receiving `Authentication failed because no credentials were provided`. Might be Xcode issue, but probably anybody else had this.

### Reproduction

Add Swift Package Manager dependency via ssh: git@github.com:auth0/JWTDecode.swift.git

### Environment
- JWTDecode.swift version 2.4.1
- Xcode 11.4.1

**Comment by Widcket** [comment]
Hi @denys-meloshyn, that looks like a configuration issue on your end. You can try `git config --global url."git@github.com:".insteadOf "https://github.com/"`.

**Comment by dolzhenko-tony** [comment]
@Widcket  thanx for reply, I had config file corrupted
