### ISSUE TITLE
Tag 9.9.9 breaks SwiftPM version support

### ISSUE THREAD

**Issue by ksullivan1-chwy** [auth0/JWTDecode.swift#112]
SwiftPM uses tags conforming to semver to determine release builds. The 9.9.9 tag breaks this scheme, can you please delete it?

**Comment by Widcket** [comment]
Hi @ksullivan1-chwy, you can use [upToNextMajor](https://developer.apple.com/documentation/swift_packages/package/dependency/requirement/2878218-uptonextmajor) to keep SwiftPM from picking up a new major (the 9.9.9 tag was created for testing purposes and would represent a different "major" under SemVer).
