### ISSUE TITLE
JWTDecode fails to build with Swift 5.3 (Xcode 12)

### ISSUE THREAD

**Issue by SergejLogis** [auth0/JWTDecode.swift#113]
### Describe the problem

`JWTDecode` build fails in Xcode 12.0 GM (both from IDE and by using Command Line Tools)

### What was the expected behavior?

`JWTDecode` build successful.

### Reproduction

`JWTDecode` is mandatory dependency of `Auth0.swift` library. Issue was observed while trying to build `Auth0.swift` with Swift 5.3 compiler:
1. Swifch to Xcode 12 Command Line tools.
2. Checkout `Auth0.swift`
3. Run `carthage build --platform ios`
4. Observe `JWTDecode` build failure. There is no clear error in log file, it says `ARCHIVE SUCCESSFUL` and `JWTDecode` artefact created in `Carthage/Build` folder. 🤷‍♂️

### Observations
1. `JWTDecode` fails to build from Xcode 12 IDE:
<img width="854" alt="Screenshot 2020-09-18 at 12 49 27" src="https://user-images.githubusercontent.com/32644729/93584113-8688eb80-f9ad-11ea-8926-f9d3e48cb722.png">

2. `JWTDecode` builds successfully if `Nimble` version is updated to [9.0.0.rc.3](https://github.com/Quick/Nimble/tree/v9.0.0-rc.3) in `Package.swift`
```
dependencies: [
        // Dependencies declare other packages that this package depends on.
         .package(url: "https://github.com/Quick/Quick", from: "2.1.0"),
        .package(url: "https://github.com/Quick/Nimble", .revision("6956ffbde4ea6aab94fd2e823c5ede95072feef2"))
    ],
```

I have also tried switching `Nimble` to `9.0.0.rc.3` by updating `Auth0.swift`'s Cartfile.resolved:
```
github "AliSoftware/OHHTTPStubs" "9.0.0"
github "Quick/Nimble" "6956ffbde4ea6aab94fd2e823c5ede95072feef2"
github "Quick/Quick" "v2.2.0"
github "auth0/JWTDecode.swift" "2.4.1"
github "auth0/SimpleKeychain" "0.11.1"
```
And I see that Carthage resolved Nimble version properly:
<img width="1129" alt="Screenshot 2020-09-18 at 12 13 56" src="https://user-images.githubusercontent.com/32644729/93583321-5d1b9000-f9ac-11ea-8a22-78ac30687aff.png">
However, build still fails with no clear error: [carthage-xcodebuild.Elzx5t.log.zip](https://github.com/auth0/JWTDecode.swift/files/5244738/carthage-xcodebuild.Elzx5t.log.zip)

### Environment

- `JWTDecode.swift v2.4.1`
- `macOS 10.15.6`
- `Xcode 12.0 GM (12A7209)`

**Comment by Widcket** [comment]
@SergejLogis the JWTDecode.swift framework itself does not have dependencies, the only dependencies are for the test target that will not build under Xcode 12 because Nimble. You could just clone this repo, open it with Xcode and build the framework target and it will build just fine. Then you can build it for release, and then link it to your app.

**Comment by Widcket** [comment]
You would only need to do `carthage bootstrap` if you want to run the tests.

**Comment by Widcket** [comment]
The error you're seeing with Carthage is due to this issue: https://github.com/Carthage/Carthage/issues/3019
There is a workaround posted in the comments: https://gist.github.com/skymobilebuilds/61f4a95bd62a3db36b52719aeab7e0d5

**Comment by SergejLogis** [comment]
Thank you very much! Carthage workaround did the trick! 🙇‍♂️ 🙏

**Comment by SergejLogis** [comment]
I have added Carthage workaround, and all dependencies were built successfully. However, when I run project either on Simulator or on device I'm getting the following error:
```
error: virtual filesystem overlay file '/Users/rita/Library/Developer/Xcode/DerivedData/JWTDecode-evduuxvbogzsqoeydwuchazcbvrf/Build/Intermediates.noindex/ArchiveIntermediates/JWTDecode-iOS/IntermediateBuildFilesPath/JWTDecode.build/Release-iphonesimulator/JWTDecode-iOS.build/all-product-headers.yaml' not found
```
Any ideas why is there absolute path hardcoded somewhere in the repo? 🤔 Quick search in `Carthage/Checkouts` reveals that it also presents in multiple places in `SimpleKeychain` library. I'm using Auth0 1.28.0 from GitHub.

**Comment by Widcket** [comment]
@SergejLogis the 9.9.9 tags were created by me for test purposes. Unfortunately, the Cartfile in Auth0.swift does not pin the dependencies to the current major version, so it ended up getting those tags. I've deleted them; and will pin the dependencies in the next release of Auth0.swift.

**Comment by SergejLogis** [comment]
Thanks! Is there a way to resolve my issue in current Auth0 version (1.28)? 🤔

**Comment by Widcket** [comment]
Clean Derived Data and rebuild.

**Comment by Widcket** [comment]
Closing as this is a Carthage issue.
