### ISSUE TITLE
Handling milliseconds value comes in String

### ISSUE THREAD

**Issue by Elamuruga** [auth0/JWTDecode.swift#124]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/responsible-disclosure-policy) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem
From the API now the sending now they are sending time with milliseconds in String format. While decoding its causes a crash.  I get an error log like below

Could not cast value of type '__NSCFString' (0x25d9caf60) to 'NSNumber' (0x25d9d9588)

> Provide a clear and concise description of the issue

My sample code form decode is were as follows, Could you please help me to resolve this? and let me know if anything I missed to handle. 

 public static func getTokenExp(basestring: String) -> NSInteger {
        do {
            let jwt = try decode(jwt: basestring)
            return jwt.body["exp"] as! NSInteger
        } catch let error as NSError {
            print(error.localizedDescription)
            return 0
        }
    }

### What was the expected behavior?

> Tell us about the behavior you expected to see

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducible steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- Step 1..
- Step 2..
- ...

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log information (redact/remove sensitive information)
> - Screenshots/GIFs

### Environment

> Please provide the following:

- **Version of `JWTDecode.swift` used:**
- **Version of iOS/macOS/tvOS/watchOS:**
- **Version of Xcode:**

**Comment by Widcket** [comment]
Hi @Elamuruga, to get the value of the `exp` claim, you can use `jwt.expiresAt`(returns a `Date?`) or `jwt.claim(name: "exp").date`(returns a `Date?` as well).
Does that help?

**Comment by Widcket** [comment]
Closing this one, ping me if you still need help with this.
