### ISSUE TITLE
Expiry date is nil

### ISSUE THREAD

**Issue by bonroyage** [auth0/JWTDecode.swift#15]
Hi,

After decoding any JWT token, I would always get a `nil` value for `expiresAt` and `false` for `expired`. I managed to make it work by changing two lines of code.

```swift
// JWTDecode.swift

// Lines 67 - 72
private func claim(name: String) -> NSDate? {
	guard let timestamp:Double = Double(claim(name)!) else { // <-- wrapped claim() in Double()
		return nil
	}
	return NSDate(timeIntervalSince1970: timestamp)
}

// Lines 74 - 78
var expired: Bool {
	guard let date = self.expiresAt else {
		return false
	}
	return date.timeIntervalSinceNow.isSignMinus // <-- check if the time interval to now is negative
}
```

I am unsure whether or not I am doing something wrong in the decoding process, but my code looks something like:
```swift
import JWTDecode

// ...

let jwt = try decode(token)

if jwt.expired {
    // refresh token
}
```

Cheers.

**Comment by hzalaz** [comment]
@bonroyage can you post the base64 payload of a token that yields the `exp` as nil? (the payload is the middle part of the JWT base64)

**Comment by bonroyage** [comment]
Here's the entire token, the object (from `decode(token)`), the expiry date `jwt.expiresAt` and whether it's expired `jwt.expired`:

- **Token** `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1NWI2NDJiNDhiODIyNjI1N2FkNWUyZTIiLCJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjFcL2p3dCIsImlhdCI6IjE0NDc2OTA5MTciLCJleHAiOiIxNDQ3Njk0NTE3IiwibmJmIjoiMTQ0NzY5MDkxNyIsImp0aSI6ImVjYzQ0Y2M1NGNjZmNjOTQ4M2NlNmEwM2VhYzRjYzNkIn0.BfRKZUtuPygqm7zXAeaHU1W2c6guH3w9fQ59FGqbj68`
- **JWT object** `DecodedJWT(header: ["alg": HS256, "typ": JWT], body: ["nbf": 1447690917, "exp": 1447694517, "iss": http://127.0.0.1/jwt, "jti": ecc44cc54ccfcc9483ce6a03eac4cc3d, "iat": 1447690917, "sub": 55b642b48b8226257ad5e2e2], signature: Optional("BfRKZUtuPygqm7zXAeaHU1W2c6guH3w9fQ59FGqbj68"))`
- **Expires at** `nil`
- **Expired?** `false`

**Comment by hzalaz** [comment]
@bonroyage Swift 2.0 or Swift 2.1?

**Comment by bonroyage** [comment]
Swift 2.1

**Comment by hzalaz** [comment]
@bonroyage the value of the `exp` claim should be a integer not a string value (the same goes for `nbf`, `iat`), your are building the offending tokens yourself or you got those from another source (e.g. Auth0 or another service)?

**Comment by bonroyage** [comment]
I am using this library for Laravel https://github.com/tymondesigns/jwt-auth. After testing the code, I can confirm that it uses strings. I could open an issue in that repo and ask them to change it to integers. Or would it be possible for you to force cast them as Doubles so any other package that happens to use strings also works.

**Comment by hzalaz** [comment]
@bonroyage the [spec](https://tools.ietf.org/html/rfc7519) defines them as numbers so even if I could hack for string values, I'd prefer to stick to it.

**Comment by bonroyage** [comment]
Alright, I'll PR the PHP package. Thanks for the help!
