### ISSUE TITLE
Is this valid swift code `let jwt = try decode(token)`?

### ISSUE THREAD

**Issue by elgs** [auth0/JWTDecode.swift#17]
When I put this line `let jwt = try decode(token)` in my code, it doesn't compile. Is it valid Swift code?

**Comment by elgs** [comment]
It works when being wrapped inside a do catch block.

**Comment by minamichel17** [comment]
do
           {
            let jwt = try decode(me!["refreshToken"] as! String)
            print("JWT",jwt.expiresAt)
            
            }
            catch let error as NSError {
             error.localizedDescription
            }
