### ISSUE TITLE
Next JWTDecode.swift major release

### ISSUE THREAD

**Issue by Widcket** [auth0/JWTDecode.swift#171]
Hello! 👋 

Today we published the JWTDecode.swift 3.0.0 [First Availability release](https://github.com/auth0/JWTDecode.swift/releases/tag/3.0.0-fa).

**The GA release is planned for the third week of July.**

### Summary

- Dropped support for Objective-C.
- Dropped support for older platform and Swift versions.
- Removed ID token validator.
- Added a convenience subscript for accessing claims.
- Improved the API documentation.

### Documentation

- [README](https://github.com/auth0/JWTDecode.swift/tree/fa#readme)
- [Migration Guide](https://github.com/auth0/JWTDecode.swift/blob/fa/V3_MIGRATION_GUIDE.md)
- [Changelog](https://github.com/auth0/JWTDecode.swift/blob/fa/CHANGELOG.md)
- [API documentation](https://auth0.github.io/JWTDecode.swift/documentation/jwtdecode/)

### Feedback

We’d love for you to give the FA release a try, and welcome your feedback on any recommendations or issues you encounter. Should you have any feedback or questions, please [raise an issue](https://github.com/auth0/JWTDecode.swift/issues/new/choose).

**Comment by evansims** [comment]
🤖 Commenting to filter for internal tooling. Please disregard.

**Comment by Widcket** [comment]
The v3 release is out now! https://github.com/auth0/JWTDecode.swift/releases/tag/3.0.0
