### ISSUE TITLE
Package resolution failed

### ISSUE THREAD

**Issue by SatishKishorbhai** [auth0/JWTDecode.swift#183]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/JWTDecode.swift#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/JWTDecode.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tags/c/sdks/5/jwt) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

While try to add this library using PDM it gives error and not able to add PDM.
Please find the screen shot

<img width="684" alt="Screen Shot 2022-07-29 at 3 14 53 PM" src="https://user-images.githubusercontent.com/91555423/181733334-a25b09ea-43f0-4869-b0d4-14ab1a0e307a.png">

### Reproduction

1)Create new project
2)Go to project
3)Click on Swift Packages section and try to add 
https://github.com/auth0/JWTDecode.swift
with 3.0.0 version

### JWTDecode.swift version

3.0.0

### Platform

iOS

### Platform version(s)

14.3

### Xcode version

12.4

### Package manager

SPM

**Comment by Widcket** [comment]
Hi @SatishKishorbhai, thanks for raising this. I just created a new app, and installed JWTDecode.swift, then built the app successfully:

https://user-images.githubusercontent.com/5055789/181773263-8e51f470-efca-4951-bc46-cc692a12f14a.mov

**Comment by SatishKishorbhai** [comment]
@Widcket can you please check with Xcode 12.4

**Comment by Widcket** [comment]
Xcode 12.x is not supported anymore.

**Comment by SatishKishorbhai** [comment]
> Xcode 12.x is not supported anymore.

https://user-images.githubusercontent.com/91555423/182154120-af271b93-cec6-4e07-901b-96f5db11c3cf.mov

**Comment by Widcket** [comment]
"contains incompatible tools version" is because the [Package.swift requires](https://github.com/auth0/JWTDecode.swift/blob/master/Package.swift#L1) at least Swift 5.5, which was introduced with Xcode 13.0.

**Comment by Widcket** [comment]
That seems to clarify the issue. As mentioned, Xcode 12.x is not mentioned anymore. I'll close this issue, please feel free to ping if you'd prefer to reopen.
