### ISSUE TITLE
Add privacy manifest

### ISSUE THREAD

**Issue by yasiraliraj** [auth0/JWTDecode.swift#223]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/JWTDecode.swift#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/JWTDecode.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The primary issue I'm encountering involves the lack of a feature for handling privacy manifests within the JWTDecode.swift library. As per the new App Store guidelines effective from May 1, 2024, all applications are required to include a privacy manifest. This is crucial for ensuring that our app remains compliant with App Store policies and avoids any potential disruption in service or availability on the App Store.

### Describe the ideal solution

The optimal solution would be for JWTDecode.swift to integrate a feature that allows for easy creation and management of privacy manifests in accordance with the upcoming App Store requirements. This would ideally include functionalities to specify the data types accessed or collected by our application and any third-party integrations, ensuring a seamless process for developers to declare their app's privacy practices transparently. Such an update would greatly assist in maintaining the app's compliance and streamline the development process for all users of your library.

**Comment by dennyaby** [comment]
I haven't found any calls to APIs that require Privacy Manifest, so from my point of view Privacy Manifest is not needed for this SDK.

**Comment by Widcket** [comment]
Hi @yasiraliraj, thanks for raising this.

The Apple docs instruct that SDKs must include a privacy manifest [in the following situations](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files#overview):

- **If Apple explicitly requires it to:** Apple published [a list of popular libraries](https://developer.apple.com/support/third-party-SDK-requirements/) deemed to be “privacy impacting“, which are required to include a privacy manifest.
- **If the SDK uses a “required reasons“ API:** Apple published [a list of system APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) that are commonly abused for fingerprinting purposes. Moving forward, the APIs in that list can only be used for legitimate, explicitly defined reasons. The usage of these APIs and the reasons for using them must be declared in the privacy manifest.
- **If the SDK collects data about the user, or enables the app to do so**
- **If the SDK contacts tracking domains:** Whenever an SDK sends collected data to a domain for tracking purposes, this domain must be declared in the privacy manifest.

<img width="947" alt="Screenshot 2024-04-11 at 23 20 36" src="https://github.com/auth0/SimpleKeychain/assets/5055789/dac87c56-bb1d-4182-801d-d46fbfb6a16a">

❌ JWTDecode.swift is not on the list of libraries published by Apple
❌ JWTDecode.swift does not use any “required reasons“ APIs
❌ JWTDecode.swift.swift does not collect any data, nor enables the app to do so
❌ JWTDecode.swift does not contact any tracking domains

Therefore, JWTDecode.swift does not need to include a privacy manifest.
Also, JWTDecode.swift is provided as a source package only, not as a binary. So, the signature requirement does not apply.
