### ISSUE TITLE
Missing Privacy manifest

### ISSUE THREAD

**Issue by pyounes** [auth0/JWTDecode.swift#226]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/JWTDecode.swift#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/JWTDecode.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Unavailable privacy manifest required by apple

### Describe the ideal solution

add it please

**Comment by desusai7** [comment]
Hi @pyounes, 

Privacy Manifest file is not required for [JWTDecode.swift](https://github.com/auth0/JWTDecode.swift) & [SimpleKeyChain](https://github.com/auth0/SimpleKeychain) as they:

* Do not use any of the reasons required APIs.
* Do not collect the user data or enable the app to do so.
* Do not contact any tracking domains.

However the file is required for our primary library [Auth0.swift ](https://github.com/auth0/Auth0.swift) and we've included it as part of the version `2.7.0` of it
