### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by treyrich** [auth0/JWTDecode.swift#27]
Would be great for testing if this library could be updated to support swift 3.

**Comment by hzalaz** [comment]
Till swift 3 is released the branch [feature-swift-3](https://github.com/auth0/JWTDecode.swift/tree/feature-swift-3) will have the swift 3 combat codebase

**Comment by bradfol** [comment]
Plans to release a new version for Swift 3 now that we have Xcode 8 GM?
