### ISSUE TITLE
Issue with time of expiration.

### ISSUE THREAD

**Issue by rlam3** [auth0/JWTDecode.swift#3]
Hi,

I'm quite new to ios development. 
I'm having a bit of trouble understanding how your isJWTExpired and expireDateOfJWT works.

My token looks like this:

eyJhbGciOiJIUzI1NiIsImV4cCI6MTQyNzQ2OTA4NSwiaWF0IjoxNDI3NDY4Nzg1fQ.eyJ1c2VyX2lkIjo0LCJuYmYiOjE0Mjc0ODY3ODIuMCwiZXhwIjoxNDI3NDg3MDgyLjB9.X1o75sv3-Iq4mk3gmHYysnkOS-CfRi4dOQ97fOq3I10

From what your code is saying, it is taking the exp from the claims section correct? So that should be 1427487082

var exp2 = NSDate(timeIntervalSince1970:1427487082.doubleValue)

When running the code through swift playground I'm getting "Mar 27, 2015, 3:11 PM" <<< UTC time.., which I believe is correct. But when I use your expiryDate method it returns back 2015-03-27 20:11:22 +0000. 

I'm a bit puzzled as to why this is happening. Is it me sending the incorrect time? 

Thanks :)

**Comment by hzalaz** [comment]
It's not the incorrect time, its a matter of how the data is displayed. Try printing the value of the property `timeIntervalSince1970` in `exp2` and what the library returns and they should be the same.
The playground prints the value of this line:

```swift
var exp2 = NSDate(timeIntervalSince1970:1427487082.doubleValue)
```
using your Mac's timezone, but if you add this line:

```swift 
exp2.description
```

you'll see it displayed in UTC

**Comment by rlam3** [comment]
@hzalaz I'm having trouble with the ".expired" part with after decoding the token. i'm getting a mismatch between what the server is sending out and what swift code is interpreting the "exp" as. Could you please explain how the ".expired" attribute works? Thanks!

**Comment by hzalaz** [comment]
It's just a timestamp and that's how it's handled, and how it explained before. The value of `exp` a numeric value, is the number of seconds since 1970 so we are using `NSDate(timeIntervalSince1970: expValue)` to get a date object. Not sure what mismatch you are talking about, possibly as I said before, it is a Tz issue and how you print the dates but if you compare them as timestamp they should be the same.
