### ISSUE TITLE
arm64 problem

### ISSUE THREAD

**Issue by antonioreyna** [auth0/JWTDecode.swift#37]
Hello, I started to get this error:

```
Undefined symbols for architecture arm64:
  "(extension in JWTDecode):JWTDecode.JWT.claim (name : Swift.String) -> JWTDecode.Claim", referenced from:
```

I dont know why?

**Comment by antonioreyna** [comment]
the problem happens when i try to run it for device

**Comment by hzalaz** [comment]
I can't do much with that little info, can you build a sample project so I can take a look? Or at least detail how you added the library, the dependency management tool you used, etc.

**Comment by antonioreyna** [comment]
I added the library using cocoapods `pod 'JWTDecode', '~> 1.0'`, and i noticed the problem right after i added another library the pod 'GoogleIDFASupport'

**Comment by antonioreyna** [comment]
Hello, the problem was the Derived Data directory i had to clean it manually and recompile, now its working. thanks!
