### ISSUE TITLE
Swift 2.x

### ISSUE THREAD

**Issue by carlhunterroach** [auth0/JWTDecode.swift#38]
Which previous version do you recommend for those who are immediately moving to Swift 3.0?

**Comment by hzalaz** [comment]
Not sure I understand your question but https://github.com/auth0/JWTDecode.swift/releases/tag/2.0.0 is for Swift 3
and https://github.com/auth0/JWTDecode.swift/releases/tag/1.2.0 for Swift 2.3 as the changelog specifies.

If you move to swift 3 immediately you can use 2.0.0 directly after migrating

**Comment by carlhunterroach** [comment]
Thanks. I'll try v1.2.0 as my project has dependencies that don't yet support Swift 3.0
Do you know if Auth0 has dropped support for Swift 2.x?
