### ISSUE TITLE
Pod is not Swift 3 compliant

### ISSUE THREAD

**Issue by eightamrock** [auth0/JWTDecode.swift#39]
This pod is not compiling for me using swift 3. Its noting a tremendous number of swift 3 errors. Notably lots of public to open declarations on extendable class methods. 

Is anyone else having this issue?

**Comment by hzalaz** [comment]
What version of the lib are you using?

**Comment by eightamrock** [comment]
Attempting to use 2.0.0.

**Comment by hzalaz** [comment]
@eightamrock are you sure? just tried and complies. Can you provide a sample where I can reproduce  those compile errors? (or Podfile & Podfile.lock or Cartfile & Cartfile.resolved)

**Comment by eightamrock** [comment]
Pod and lock attached. I just started a brand new project in xcode 8, setup JWTDecode as a pod, installed it and it gave me the same errors. 

[pod.zip](https://github.com/auth0/JWTDecode.swift/files/485852/pod.zip)

**Comment by hzalaz** [comment]
@eightamrock Can you send me a link to that project?. Did the same and works for me

**Comment by eightamrock** [comment]
https://github.com/eightamrock/test-ios-project

The build fails.  When you try update to swift 3.0, it gives JWTDecode a lot of errors. I tried setting use legacy to true for the framework, and it didnt help either. Ive done this on 2 different computers now, so I must be doing something wrong if you are getting it to compile. 

<img width="254" alt="screen shot 2016-09-21 at 4 18 05 pm" src="https://cloud.githubusercontent.com/assets/164820/18727611/6bfce3d4-8017-11e6-873b-9c5a28e877f1.png">

**Comment by eightamrock** [comment]
Any thoughts on this? I've successfully reverted to Swift 2.3 using JWTDecode 1.2 and everything compiles without issue. I can't get swift 3.0 to compile with JWTDecode 2.0.

**Comment by hzalaz** [comment]
JWTDecode 2.0.0 is Swift 3 compatible. Your Xcode project did not specify which Swift version to use with the settings `Use Legacy Swift Language Version`. 
Xcode migration tool will probably help you transition properly to Swift 3 and I'd use the latest rc of CocoaPods since they had some issues when figuring out what Swift version to use.
