### ISSUE TITLE
Check for invalid token?

### ISSUE THREAD

**Issue by Mapamatician** [auth0/JWTDecode.swift#40]
Would it be possible to listen for jwt.invalid on Swift?

Maybe there is a better way but here is the problem I'm trying to solve:

In my Laravel (5.3) application I am trying to log the iOS user out. 

Swift: 
    @IBAction func logout(_ sender: UIButton) {
        print("hit logout")
        
        // need to call the token again
        let token: String! = KeychainWrapper.standard.string(forKey: "jwtoken")
        
        // create the header for the request
        let headers: HTTPHeaders = ["Authorization": "Bearer" + " " + token]
        
        // fire the get user data request
        Alamofire.request("https://mydomain.com", headers:headers).response in { 
               print("Logout - HTTP URL Response: \(response.response)")
        }
```

Laravel:
Maybe there is a better way someone can recommend?
```
    public function logout() {
        $token = JWTAuth::getToken();
        JWTAuth::invalidate($token);
    }
```

The error here returns {"error":"token_invalid"}
Would it be possible to listen for this with jwt.invalid ?

**Comment by hzalaz** [comment]
@Mapamatician I'd say you need to listen to that error in the Alamofire callback, this library, sadly, won't help you with that. API tokens should be opaque to clients so I'd recommend not trying to decode them and just react when the request to the protected resource fails.

Not sure how you obtain the api token but e.g. OAuth also returns an `expires_in` attribute in the response that can be useful to use to know when the token expires. If the token is invalidated by another reason you are mostly reduced to check the request failure.
