### ISSUE TITLE
target 8.0 and swift 3

### ISSUE THREAD

**Issue by ali-hamad** [auth0/JWTDecode.swift#41]
Hi ,
is there any pod version that support "target 8.0 and swift 3"

**Comment by cocojoe** [comment]
The current [Podspec](https://github.com/auth0/JWTDecode.swift/blob/master/JWTDecode.podspec), states a minimum iOS Deployment of 8.0.
**s.ios.deployment_target = '8.0'**

**Comment by ali-hamad** [comment]
thanks for the note :P
i was using an older version that supports 8.3+
