### ISSUE TITLE
why do we need to try?

### ISSUE THREAD

**Issue by rlam3** [auth0/JWTDecode.swift#46]
Why do we to try? 

```
let jwt = try decode(jwt: token)    
```

**Comment by cocojoe** [comment]
decode can throw an error hence the try.
https://github.com/auth0/JWTDecode.swift/blob/master/JWTDecode/JWTDecode.swift#L35

I suggest you read up on the subject in general:
https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/ErrorHandling.html#//apple_ref/doc/uid/TP40014097-CH42-ID508
