### ISSUE TITLE
EXC_BAD_ACCESS coming from base64UrlDecode function

### ISSUE THREAD

**Issue by umosys** [auth0/JWTDecode.swift#47]
![screen shot 2017-05-24 at 8 33 23 pm](https://cloud.githubusercontent.com/assets/3169122/26399643/fdec4f68-40c0-11e7-80fc-7b28bc01b35b.png)

I got that when from this line in my code:
```
try JWTDecode.decode(jwt: token)
```

It's strange. This never happened before.

**Comment by cocojoe** [comment]
1. Is this repeatable?

If so please provide a link to a vanilla project that demonstrates this.  

Thanks

**Comment by cocojoe** [comment]
Closing, lack of follow up information.
