### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by eskerber** [auth0/JWTDecode.swift#49]
Support for Swift 4 / Xcode 9, which has a GM release as of 9/12

**Comment by cocojoe** [comment]
What is the actual issue you are facing? 

It runs fine as a dependency added to an Xcode 9 / Swift 4 project.

In general terms we are going through our libs and will update in order of priority

**Comment by cocojoe** [comment]
What is the actual issue you are facing?
It runs fine as a dependency, I just added it to an Xcode 9 / Swift 4 project.

In general terms we are going through our libs and will update in order of priority.

**Comment by treyrich** [comment]
One specific issue is that this framework includes LLVM Instrumentation which is now causing rejections from Apple.

**Comment by cocojoe** [comment]
Thanks, I had a look into this. https://github.com/Carthage/Carthage/issues/2056 
Let me sort something out.

**Comment by cocojoe** [comment]
@treyrich I updated and fixed in PR #50 please can you try out that branch and let me know thanks.

**Comment by treyrich** [comment]
Yes, using the `changed-updated-xcode9-swift-3.2` branch iTunes Connect accepted the build, looks good to me.

**Comment by cocojoe** [comment]
This is now covered in latest release https://github.com/auth0/JWTDecode.swift/releases/tag/2.1.0
