### ISSUE TITLE
Add watchOS support

### ISSUE THREAD

**Issue by chaseacton** [auth0/JWTDecode.swift#58]
Hi, please consider adding support for watchOS in the cocoapod.

**Comment by cocojoe** [comment]
Not looked into it, will add on my list of things to evaluate.

**Comment by cocojoe** [comment]
Still demand out there for this?

**Comment by chaseacton** [comment]
Yes, we would still like watch support

**Comment by jklp** [comment]
Added a pull request here but only for Carthage #91

**Comment by shayneoneill** [comment]
And Catalyst support
