### ISSUE TITLE
Support Swift package manager for server side Swift apps

### ISSUE THREAD

**Issue by kdawgwilk** [auth0/JWTDecode.swift#61]
I am working on a server side Swift project with Vapor and would like to use Auth0 but I am finding that there is a lack of support for native Swift packages that can run on Linux.  This seems like it could be a great starting point to add support for server side Swift to Auth0 since this doesn't seems to need UIKit

**Comment by cocojoe** [comment]
I've been holding off in general, waiting for some kind of UIKit support. However, for this lib you are right it could probably work for Swift Packager Manager. It's not a priority but I'll take a look at some point, although your welcome to submit a PR.

**Comment by cocojoe** [comment]
I'm going to add this on our internal features to review.

**Comment by cocojoe** [comment]
I've held off on SPM support waiting for maturity and UIKit support. I feel we are in a better position now with SPM to look at this.
