### ISSUE TITLE
Use of unresolved identifier when archive

### ISSUE THREAD

**Issue by skeer00** [auth0/JWTDecode.swift#62]
I am working in a project where cocopod is not integrated. I downloaded the JWTDecode project and added the JWTDecode.framework into our project. I got the JWTDecode.framework file when I run the sample project added JWTDecode project as cocoapod. So my project works well in simulator, I am able to decode the JWT token and get the claims. But when I trying to build/archive project it gives me an error Use of unresolved identifier 'decode'. Can you help me on this?

**Comment by cocojoe** [comment]
We support Carthage and Cocoapods, if you are manually integrating, I can't really help as there are so many possible variables involved.
