### ISSUE TITLE
JWT validation

### ISSUE THREAD

**Issue by dj-neza** [auth0/JWTDecode.swift#64]
Hi! 
Any plans to extend the library to support JWT validation in Swift as well?

**Comment by cocojoe** [comment]
What do you mean? It's a swift library.

**Comment by dj-neza** [comment]
I know, but it only decodes the JWT without verifying it right?

**Comment by cocojoe** [comment]
I understand your question, can we expand this library to support validation not just decoding?

**Comment by dj-neza** [comment]
Yes, that's exactly what I've been asking. So is there any possibility of that?

**Comment by cocojoe** [comment]
There are some plans related around validation, so it is a possibility. However, I can't really tell you anymore than that right now.

**Comment by cocojoe** [comment]
So yes is the answer, will be starting this soon. 👍

**Comment by cocojoe** [comment]
Claims validation was added in https://github.com/auth0/JWTDecode.swift/releases/tag/2.2.0
