### ISSUE TITLE
Claims value nil, but payload seems fine

### ISSUE THREAD

**Issue by DeathByEnnui** [auth0/JWTDecode.swift#65]
I can print out my idToken, cut and paste it into https://jwt.io and I see all my payload data, but when I try to use JWTDecode I'm getting all nil values for my claims.

```
        do {
            let jwt = try decode(jwt: idToken)

            let lastNameClaim = jwt.claim(name: "lastName")
            if let lastName = lastNameClaim.string {
                print("Last name in jwt was \(lastName)")
            }

            let claim = jwt.claim(name: "userID")
            if let email = claim.string {
                print("Email in jwt was \(email)")
            }
        } catch {
            print("JWT fail: \(error.localizedDescription)")
        }
```

Nothing prints and I stick a breakpoint into the debugger I see the claim.value is nil. Looking at `jwt.body` shows my custom attributes in `custom_attributes` Dictionary as expected. Here is an example ID token (signature removed for smaller sizing)

```
eyJraWQiOiIyMTIiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoicVpxOXRLN0dWME81ZFZnQWtGSVpYdyIsInN1YiI6Imh0dHBzOi8vdGVzdC5zYWxlc2ZvcmNlLmNvbS9pZC8wMEQyNTAwMDAwMERxU2NFQUsvMDA1MjUwMDAwMDJ1M29vQUFBIiwiYXVkIjoiM01WRzlyS2hUOG9jb3hHazFFbkZLVGZ2TXZjRV9xQy5hMEQ5S0VpR2VOQmJiaHRHd2h1c2VfWjRENlAuN1pfRnVWMEFjWFRfakhYeVFDc2lOOUk0aCIsImlzcyI6Imh0dHBzOi8vdGVzdC1tdGwuY3M4MC5mb3JjZS5jb20vIiwiZXhwIjoxNTIzNTUyMDYxLCJpYXQiOjE1MjM1NTE5NDEsImN1c3RvbV9hdHRyaWJ1dGVzIjp7Imxhc3ROYW1lIjoiTWFjayIsImZpcnN0TmFtZSI6IkRhdmlkIiwiZmVkZXJhdGlvbklEIjoiRkVELTAwMTM3NzU4NDIiLCJ1c2VySUQiOiJkYXZpZC5tYWNrQHRldmFwaGFybS5jb20ifX0
```

Any help appreciated.

**Comment by lbalmaceda** [comment]
![image](https://user-images.githubusercontent.com/3900123/38692764-3965d1d4-3e5b-11e8-9ba4-044b00ad1681.png)

The token you shared has those claims nested inside a "custom_attributes" claim.

**Comment by DeathByEnnui** [comment]
My mistake then. I thought all custom attributes were encoded into the custom_attributes claim, but obviously I was mistaken. Thank you for the clarification.
