### ISSUE TITLE
Make Claim.value public

### ISSUE THREAD

**Issue by DeathByEnnui** [auth0/JWTDecode.swift#67]
Right now Claim.value is not public. There is no direct way to pull out something like a Dictionary type directly. The simplest way would be to use .value and cast it, but it's not visible.

**Comment by suzukieng** [comment]
Agree, we use JWT to transport the users authorizations. This is an array, with the value being a complex type (role, entity)

**Comment by cocojoe** [comment]
This seems fair, I'm thinking

```swift
    /// original claim value
    public var rawValue: Any? {
        return self.value
    }
```

**Comment by suzukieng** [comment]
@cocojoe Feels right! raw implying that you're on your own if you're using it.

**Comment by suzukieng** [comment]
@cocojoe any ETA on when we can get this merged?

**Comment by cocojoe** [comment]
Sorry forgot about this, merged.
