### ISSUE TITLE
Minimum iOS version for 2.1.1?

### ISSUE THREAD

**Issue by leolobato** [auth0/JWTDecode.swift#72]
The README page mentions iOS 9+ is required, but the Podspec specifies iOS 8.0.0 -- so 2.1.1 will be installed on a project with deployment target less than 9.

Which one is true?

**Comment by cocojoe** [comment]
The real source of truth is the project itself, which states iOS 8.0. So Podspec is aligned with this. Are you still using iOS 8 as a minimum deploy?

**Comment by leolobato** [comment]
Thanks!

Only one of the projects I work at is still at iOS 8 -- but I suspect it should be bumped to iOS 9 soon (since any device that supports iOS 8 also supports iOS 9).

**Comment by cocojoe** [comment]
This has been bumped to 9.0 now 👍
