### ISSUE TITLE
Problem with error handling with iOS 10

### ISSUE THREAD

**Issue by daxe72** [auth0/JWTDecode.swift#73]
Errors.swift

Identifier Name Violation: Enum element name should only contain alphanumeric characters: 'invalidBase64Url(_:)' (identifier_name)

**Comment by cocojoe** [comment]
Sounds more like SwiftLint, there are no issues linting this Library using latest SwiftLint. Unless you have your own ruleset which overrides this?

**Comment by daxe72** [comment]
Ok, I will try with the latest SwiftLint library

**Comment by daxe72** [comment]
That solves it.
