### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by kimdv** [auth0/JWTDecode.swift#85]
In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please user the [Auth0 Community](https://community.auth0.com/).

### Description

Description of the bug or feature request and why it's a problem. Consider including:

- The use case or overall problem you're trying to solve
- Information about when the problem started

### Prerequisites

* [x] Did you check the documentation? [Add a link]
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate Issues or PRs for this issue?

### Environment

Please provide the following:

- JWTDecode.swift version 2.2
- iOS version 12.2
- If using Carthage or CocoaPods: Cartfile
- Xcode version 10.2

As Swift 5 is released with Xcode 10.2 is there any plans to update to Swift 5

**Comment by cocojoe** [comment]
Not tried it yet, is there an actual issue such as compiler error? Thanks

**Comment by kimdv** [comment]
No no error. 
Is is only for benefits of Swift 5

**Comment by cocojoe** [comment]
Added #88
