### ISSUE TITLE
Carthage fails

### ISSUE THREAD

**Issue by lifely** [auth0/JWTDecode.swift#9]
Hello,

I was trying to use JWTDecode in a swift project today. Unfortunately i'm having issue installing it using carthage.

using the following line in a newly create `Cartfile` file : 

```
jdimarco@jdimarco-eth tmp $ mkdir test
jdimarco@jdimarco-eth tmp $ cd test/
jdimarco@jdimarco-eth test $ echo "github \"auth0/JWTDecode.swift\"" > Cartfile
jdimarco@jdimarco-eth test $ cat Cartfile 
github "auth0/JWTDecode.swift"
jdimarco@jdimarco-eth test $ carthage update
*** Fetching JWTDecode.swift
A shell task failed with exit code 128:
fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository

jdimarco@jdimarco-eth test $ 
```

I don't really know what's the issue if it's carthage or this project configuration.

**Comment by hzalaz** [comment]
Seems to be a Carthage issue and it's working for me

<img width="762" alt="screenshot 2015-08-03 15 54 43" src="https://cloud.githubusercontent.com/assets/895992/9045217/18915132-39f8-11e5-83ee-87054a835c59.png">

Did it only fail with JWTDecode?

Also, try cleaning up Carthage cache with this command `rm -rf ~/Library/Caches/org.carthage.CarthageKit` and then run `carthage update`

**Comment by hzalaz** [comment]
Closing this, please reopen if still failing
