### ISSUE TITLE
Swift Package Manger support?

### ISSUE THREAD

**Issue by SlashDevSlashGnoll** [auth0/JWTDecode.swift#92]
In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please user the [Auth0 Community](https://community.auth0.com/).

### Description

XCode11 comes with native support for SPM for all project types.  This will quickly become the preferred way to manage dependencies.  JWTDecode could easily support SPM as it exists today and require no changes when XCode11 goes live to support its usage of SPM.

### Prerequisites

* [x] Did you check the documentation? [Add a link]
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate Issues or PRs for this issue?

### Environment

Please provide the following:

- JWTDecode.swift version 2.2.0
- iOS version 12.2
- If using Carthage or CocoaPods, please include your Cartfile or Podfile N/A
- Xcode version 10.2

### Reproduction

- In the add swift package dialog in XCode 11 enter the repo url: https://github.com/auth0/JWTDecode.swift.git
- Press next
- Select the latest version
- See the following error: "https://github.com/auth0/JWTDecode.swift.git has no Package.swift manifest for version 2.3.0"

**Comment by cocojoe** [comment]
I agree with you, it looks like Xcode11 will finally deliver a good SPM story. Will leave this open to track and add internally to feature requests.

**Comment by SlashDevSlashGnoll** [comment]
Thanks!  Glad to hear it.  I'm looking forward to jettisoning Pods this fall 👍

**Comment by rosskimes** [comment]
Any update on this now that Xcode 11 GM is out?

**Comment by sfla** [comment]
Our team would also appreciate this!

**Comment by frederic-c-dcode** [comment]
> Our team would also appreciate this!
Mee too

**Comment by cocojoe** [comment]
It's on the cards, would like to add SPM support to all our iOS libs, sorry I don't have an ETA right now.

**Comment by dolzhenko-tony** [comment]
<img width="628" alt="Screenshot 2020-04-23 at 14 14 17" src="https://user-images.githubusercontent.com/5227857/80094142-6e33b280-856e-11ea-9a80-24ee96497a89.png">

Test target dependencies not installing if SSH used.  Receiving `Authentication failed because no credentials were provided`. Might be Xcode issue, but probably anybody else had this.
